"""Initial migration.

Revision ID: d01e31b25890
Revises: 
Create Date: 2020-08-15 21:43:47.300051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01e31b25890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('logged_in', sa.Boolean(), nullable=True),
    sa.Column('auth_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_key')
    )
    op.create_table('satisfaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=False),
    sa.Column('amount_earned', sa.Integer(), nullable=True),
    sa.Column('buildings_sold', sa.Integer(), nullable=True),
    sa.Column('date_employed', sa.String(), nullable=False),
    sa.Column('ssn', sa.Integer(), nullable=False),
    sa.Column('clientSatisfaction', sa.Integer(), nullable=True),
    sa.Column('sacked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clientSatisfaction'], ['satisfaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('love', sa.Integer(), nullable=False),
    sa.Column('apartment_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sold_by', sa.String(), nullable=True),
    sa.Column('purchased_by', sa.String(), nullable=True),
    sa.Column('clientSatisfaction', sa.Integer(), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=False),
    sa.Column('for_sale', sa.Boolean(), nullable=False),
    sa.Column('for_rent', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighbourhood', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('property_status', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('no_of_bedrooms', sa.Integer(), nullable=False),
    sa.Column('no_of_bathrooms', sa.Integer(), nullable=False),
    sa.Column('area_size', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('no_of_garages', sa.Integer(), nullable=False),
    sa.Column('year_built', sa.String(), nullable=False),
    sa.Column('video_tour', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_file2', sa.String(length=20), nullable=False),
    sa.Column('photo_data2', sa.LargeBinary(), nullable=True),
    sa.Column('image_file3', sa.String(length=20), nullable=False),
    sa.Column('photo_data3', sa.LargeBinary(), nullable=True),
    sa.Column('front_plan_file', sa.String(length=20), nullable=False),
    sa.Column('front_plan_photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('second_price', sa.Integer(), nullable=True),
    sa.Column('size_prefix', sa.String(), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clientSatisfaction'], ['satisfaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('dob', sa.String(), nullable=False),
    sa.Column('phone_no', sa.Integer(), nullable=False),
    sa.Column('criminal_record', sa.Boolean(), nullable=True),
    sa.Column('ssn', sa.Integer(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('date_comment', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('client')
    op.drop_table('apartment')
    op.drop_table('agent')
    op.drop_table('satisfaction')
    op.drop_table('admin')
    # ### end Alembic commands ###
